### ISSUE TITLE
Include in official release

### ISSUE THREAD

**Issue by alonam** [fatihboy/AnyStatusElasticsearch#1]
Hey @fatihboy 
Awesome work! Really cool!
Can we include it in the official release (using nuget)?

**Comment by fatihboy** [comment]
for sure

**Comment by alonam** [comment]
The way I'm integrating packages today is using NuGet (I noticed you already have a nuspec file) and AppVeyor to build and publish the packages. Then the Dekstop/VS apps are pulling the packages from NuGet.

You can publish the package yourself or can I fork the repository to AnyStatus organization and publish the package from there (preferred)?

You're also welcome to join our team on GitHub :-)

Thanks!

**Comment by alonam** [comment]
I'm also looking for ways to update those packages *after the app has been installed...

**Comment by alonam** [comment]
Great! I see the package is now available on NuGet...

**Comment by fatihboy** [comment]
I've publish the package over Nuget.org, but you're also welcome to fork the repo. It's my please to join the team.

**Comment by alonam** [comment]
Excellent, I've read your code, really nice work.
I've forked the repo, just for backup and and I'll add the package to the official release in upcoming releases. I'll gladly add you to the team, it may take a few days (not sure it's free).

Thank you very much for sharing and contributing!

**Comment by alonam** [comment]
I've sent you an invitation to join the team
Welcome to the team 🥇

**Comment by fatihboy** [comment]
accepted

**Comment by alonam** [comment]
Please note that I can't allow System.Diagnostics.DiagnosticSource or telemetry from the plugins due to the terms of service and privacy statement

**Comment by fatihboy** [comment]
It comes from official Elasticsearch.Net nuget package. Please refer https://www.nuget.org/packages/Elasticsearch.Net/ for dependency details.

**Comment by fatihboy** [comment]
Issue Created=> #2 
a light elascticsearch client will be implemented

**Comment by fatihboy** [comment]
Published 0.2.11 version on [nuget.org](https://www.nuget.org/packages/AnyStatus.Plugins.Elasticsearch/0.2.11) with no System.Diagnostics.DiagnosticSource dependency.

**Comment by AlonAm** [comment]
@fatihboy can you please re-publish the latest version? (last build failed)
Current version can't be registered by SimpleInjector due to the two public constructors in StoreSizeMetricQuery.cs

**Comment by fatihboy** [comment]
Published v0.2.12 with commit https://github.com/fatihboy/AnyStatusElasticsearch/commit/184f230f69ecf98ed10a49ea35f05f8d73e06bb7

**Comment by alonam** [comment]
Thanks!

**Comment by alonam** [comment]
I've added both packages and now I'm working on including assemblies and licenses in the installation package.

**Comment by alonam** [comment]
A new (unstable) version 2.7.21 has been released for testing.
The new version includes both Redis and Elasticsearch plugins and a few other minor changes.
Please give it a try and let me know what you think
https://www.anystat.us/downloads

**Comment by alonam** [comment]
Not sure if you already know,
Widgets can add child-widgets at run-time.
If the child widget is ISchedulable, AnyStatus will start monitoring that widget.

We're using this technique in [Azure DevOps](https://github.com/AnyStatus/AzureDevOps/blob/master/src/AnyStatus.Plugins.AzureDevOps/Releases/ReleaseHealthCheck.cs) and [Jenkins View](https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/Widgets/DevOps/Jenkins/View/JenkinsViewStatus.cs) plugins to automatically discover and synchronize a Tree of information. 

For example, in the screenshot below, the Desktop widget was configured once and the widgets below were created at run-time according to the information found on the remote server (Azure DevOps).
If a new Release Environment is created on Azure DevOps, it will be added to the list when the Desktop widget is refreshed.

![image](https://user-images.githubusercontent.com/3127610/63217359-c7308880-c14d-11e9-96fd-cad03f99eba6.png)

**Comment by fatihboy** [comment]
> 
> 
> A new (unstable) version 2.7.21 has been released for testing.
> The new version includes both Redis and Elasticsearch plugins and a few other minor changes.
> Please give it a try and let me know what you think
> https://www.anystat.us/downloads

Great. I've already install it. elasticsearch is ok. will check redis..

by the way, I've push newer version 0.4.23 (https://www.nuget.org/packages/AnyStatus.Plugins.Elasticsearch/0.4.23) for elasticsearch plugin with some new widgets & ui tweeks.

**Comment by fatihboy** [comment]
> 
> 
> Not sure if you already know,
> Widgets can add child-widgets at run-time.
> If the child widget is ISchedulable, AnyStatus will start monitoring that widget.
> 
> We're using this technique in [Azure DevOps](https://github.com/AnyStatus/AzureDevOps/blob/master/src/AnyStatus.Plugins.AzureDevOps/Releases/ReleaseHealthCheck.cs) and [Jenkins View](https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/Widgets/DevOps/Jenkins/View/JenkinsViewStatus.cs) plugins to automatically discover and synchronize a Tree of information.
> 
> For example, in the screenshot below, the Desktop widget was configured once and the widgets below were created at run-time according to the information found on the remote server (Azure DevOps).
> If a new Release Environment is created on Azure DevOps, it will be added to the list when the Desktop widget is refreshed.
> 
> ![image](https://user-images.githubusercontent.com/3127610/63217359-c7308880-c14d-11e9-96fd-cad03f99eba6.png)

I've reviewed & used [GitHubIssuesQuery](https://github.com/AnyStatus/Plugins/blob/65211b8ed0989a8f4ad41baf7db5236d08b4a19a/src/AnyStatus.Plugins/Widgets/DevOps/GitHub/v2/GitHubIssuesQuery.cs) code for my [IndexCountWidget](https://github.com/fatihboy/AnyStatusElasticsearch/blob/master/AnyStatus.Plugins.Elasticsearch/Index/IndexCount/IndexCountMetricQuery.cs). I'll check JenkinsViewStatus also.

**Comment by alonam** [comment]
The Azure DevOps Release is a better example because it uses the IUIAction while adding or removing noded. IUIAction is for running actions on the UI thread.

**Comment by fatihboy** [comment]
By the way, Is there any sample for drawing a line chart with unlimited upper bound? I've found some with limit of 0-100 (percentage) which is not my case (also not worked as expected)

Should I implement a logic like [UpdateHistory ](https://github.com/AnyStatus/AzureDevOps/blob/5024a55c9e71731af172a74809ed674da874dd23/src/AnyStatus.Plugins.AzureDevOps/Releases/ReleaseHealthCheck.cs#L49) in AzureDevOps?

**Comment by alonam** [comment]
Just remove the MaxValue like in https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/Widgets/SystemInformation/Network/ActiveTcpConnections.cs

Though, In some cases the chart exceeds the widget boundaries. There is an open bug on this.

**Comment by fatihboy** [comment]
> 
> 
> > A new (unstable) version 2.7.21 has been released for testing.
> > The new version includes both Redis and Elasticsearch plugins and a few other minor changes.
> > Please give it a try and let me know what you think
> > https://www.anystat.us/downloads
> 
> Great. I've already install it. elasticsearch is ok. will check redis..
> 
> by the way, I've push newer version 0.4.23 (https://www.nuget.org/packages/AnyStatus.Plugins.Elasticsearch/0.4.23) for elasticsearch plugin with some new widgets & ui tweeks.

Redis also works as expected.

**Comment by fatihboy** [comment]
> 
> 
> Just remove the MaxValue like in https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/Widgets/SystemInformation/Network/ActiveTcpConnections.cs
> 
> Though, In some cases the chart exceeds the widget boundaries. There is an open bug on this.

I also hit that bug & [replaced Sparkline with Metric](https://github.com/fatihboy/AnyStatusRedis/commit/f8f817f8f6c2be99cfaa48573d28c3edea7db7fc#diff-e7e501d617bca35469fb1f2577ffdae1).

**Comment by alonam** [comment]
Sparkline bug [#158](https://github.com/AnyStatus/Support/issues/158) fixed in 2.7.25

**Comment by alonam** [comment]
Another general comment (apologies this isn't documented yet),
If you're implementing a widget that maintains a child list.
There's a new utility called [CollectionSynchronizer](https://github.com/AnyStatus/API/blob/d899d331d596045074a76257d18658b279855ea5/src/AnyStatus.API/Common/Utils/CollectionSynchronizer.cs) that you can use to sync two lists (remote and local).
See [GitHub Issues Widget](https://github.com/AnyStatus/Plugins/blob/7312c04d60516a155edc622be09c08d22db7abba/src/AnyStatus.Plugins/Widgets/GitHub/v2/GitHubIssuesQuery.cs#L28) for example.

**Comment by alonam** [comment]
There's an issue in 0.4.23

Types 'AnyStatus.Plugins.Elasticsearch.Index.StoreSize.StoreSizeWidget' and 'AnyStatus.Plugins.Elasticsearch.StoreSize.StoreSizeWidget' both use the XML type name 'StoreSizeWidget'.

You can use the [XmlType](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmltypeattribute?view=netframework-4.8) attribute to give them unique names ([example](https://github.com/AnyStatus/AzureDevOps/blob/master/src/AnyStatus.Plugins.AzureDevOps/Releases/ReleaseWidget.cs)).

**Comment by fatihboy** [comment]
> 
> 
> Another general comment (apologies this isn't documented yet),
> If you're implementing a widget that maintains a child list.
> There's a new utility called [CollectionSynchronizer](https://github.com/AnyStatus/API/blob/d899d331d596045074a76257d18658b279855ea5/src/AnyStatus.API/Common/Utils/CollectionSynchronizer.cs) that you can use to sync two lists (remote and local).
> See [GitHub Issues Widget](https://github.com/AnyStatus/Plugins/blob/7312c04d60516a155edc622be09c08d22db7abba/src/AnyStatus.Plugins/Widgets/GitHub/v2/GitHubIssuesQuery.cs#L28) for example.

I've saw that usage & already used on [IndexCountWidget](https://github.com/fatihboy/AnyStatusElasticsearch/blob/2386bf75af97ba4bd004ca03a090cde632504e3d/AnyStatus.Plugins.Elasticsearch/Index/IndexCount/IndexCountMetricQuery.cs#L91)

**Comment by fatihboy** [comment]
> 
> 
> There's an issue in 0.4.23
> 
> Types 'AnyStatus.Plugins.Elasticsearch.Index.StoreSize.StoreSizeWidget' and 'AnyStatus.Plugins.Elasticsearch.StoreSize.StoreSizeWidget' both use the XML type name 'StoreSizeWidget'.
> 
> You can use the [XmlType](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmltypeattribute?view=netframework-4.8) attribute to give them unique names ([example](https://github.com/AnyStatus/AzureDevOps/blob/master/src/AnyStatus.Plugins.AzureDevOps/Releases/ReleaseWidget.cs)).

fixed with [v0.5.25](https://www.nuget.org/packages/AnyStatus.Plugins.Elasticsearch/0.5.25)

**Comment by fatihboy** [comment]
Is there any way to write kb/mb/gb values to marked area while stil use bytes on sparkline?
![values](https://user-images.githubusercontent.com/1845475/63231142-f6172f00-c21f-11e9-9a5a-6caca1a08292.png)

**Comment by fatihboy** [comment]
> 
> 
> Sparkline bug [#158](https://github.com/AnyStatus/Support/issues/158) fixed in 2.7.25

Redis plugin [v0.2.17](https://www.nuget.org/packages/AnyStatus.Plugins.Redis/0.2.17) released with sparklines. (except used memory & used rss widgets)

**Comment by alonam** [comment]
Redis 0.217 and ES 0.5.25 released in 2.7.27
