### ISSUE TITLE
Remove Nest dependency

### ISSUE THREAD

**Issue by fatihboy** [fatihboy/AnyStatusElasticsearch#2]
Since System.Diagnostics.DiagnosticSource or telemetry from the plugins due to the terms of service and privacy statement is not allowed in AnyStatus, Nest nuget package dependency should be removed.

**Comment by fatihboy** [comment]
A light, purpose specific, elasticsearch client will be implemented

**Comment by alonam** [comment]
Can we disable or exclude this binary instead of replacing Nest/ES?

**Comment by fatihboy** [comment]
As long as one did not recompile and distribute nuget package binary cannot be disable nor exclude (https://github.com/elastic/elasticsearch-net/issues/3945). However it is there for debugging/logging. please refer https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/diagnostic-source.html for details.

**Comment by fatihboy** [comment]
Nest dependency removed
