### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by alonam** [fatihboy/AnyStatusElasticsearch#4]
As I was reading about what is required to include your plugins in the official release I noticed that in order to comply with the LGPL v3 license I have to open-source the entire application and everything that uses those plugins.

Can you please consider changing the license to MIT or BSD or Apache 2.0 so I will be able to distribute the plugins with the official release?

Thank you

**Comment by alonam** [comment]
As a result of this understanding I have changed the API license to Apache 2.0 so plugins won't be forced to use the same license.

**Comment by alonam** [comment]
As far as I understand, LGPL is also suitable (not sure though)

**Comment by fatihboy** [comment]
It's ok for me to provide a permissive license than copyleft. I'll probably use Apache 2.0, but first need to look ones more terms and conditions.

**Comment by alonam** [comment]
In the meantime, until we figure this out, I will release 2.7 without the new plugins.
I'd like to discuss this further with you on WhatsApp or email to explore other options

**Comment by fatihboy** [comment]
fixed with commit e41c108efd4ea26949927d86081456e13f4d0631
